# Generated by Django 5.0.2 on 2024-02-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_event_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="tag",
            new_name="category",
        ),
    ]
